[target.riscv64gc-unknown-linux-gnu]
pre-build = [
  "dpkg --add-architecture riscv64",
  "apt-get update",
  "apt-get install -y --no-install-recommends libssl-dev:riscv64 pkg-config"
]

[target.riscv64gc-unknown-linux-musl]
pre-build = [
  "dpkg --add-architecture riscv64",
  "apt-get update",
  "apt-get install -y --no-install-recommends libssl-dev:riscv64 pkg-config"
]
