name: Build For Windows

on:
  push:
    tags: 
      - 'v*'
      - 'v*-beta*'
      - 'v*-rc*'
      - 'nightly*'
  workflow_dispatch:
  pull_request:

jobs:
  build-windows-msvc-x86_64:
    name: Windows MSVC (x86_64)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install OpenSSL via vcpkg
        run: |
          vcpkg install openssl:x64-windows
          echo "OPENSSL_NO_VENDOR=1" >> $GITHUB_ENV

      - name: Build (MSVC x86_64)
        run: cargo build --release --target x86_64-pc-windows-msvc

  build-windows-gnu-x86_64:
    name: Windows GNU (x86_64)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install MSYS2 & OpenSSL (MINGW64)
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-openssl
            mingw-w64-x86_64-rust

      - name: Set OpenSSL env vars
        shell: bash
        run: |
          echo "OPENSSL_NO_VENDOR=1" >> $GITHUB_ENV
          echo "OPENSSL_DIR=/mingw64" >> $GITHUB_ENV
          echo "OPENSSL_LIB_DIR=/mingw64/lib" >> $GITHUB_ENV
          echo "OPENSSL_INCLUDE_DIR=/mingw64/include" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=/mingw64/lib/pkgconfig" >> $GITHUB_ENV
          echo "PKG_CONFIG_ALLOW_CROSS=1" >> $GITHUB_ENV

      - name: Build (GNU x86_64)
        shell: msys2 {0}
        run: cargo build --release --target x86_64-pc-windows-gnu
        
  build-windows-msvc-arm64: 
    name: Windows MSVC (ARM64)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        
      # 1. 安装 vcpkg
      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git C:\vcpkg
          C:\vcpkg\bootstrap-vcpkg.bat
          echo "VCPKG_ROOT=C:\vcpkg" >> $env:GITHUB_ENV

      # 2. 安装 ARM64 OpenSSL
      - name: Install OpenSSL (ARM64)
        run: |
          C:\vcpkg\vcpkg.exe install openssl:arm64-windows
          echo "OPENSSL_NO_VENDOR=1" >> $env:GITHUB_ENV
          echo "OPENSSL_DIR=C:\vcpkg\installed\arm64-windows" >> $env:GITHUB_ENV
          echo "OPENSSL_LIB_DIR=C:\vcpkg\installed\arm64-windows\lib" >> $env:GITHUB_ENV
          echo "OPENSSL_INCLUDE_DIR=C:\vcpkg\installed\arm64-windows\include" >> $env:GITHUB_ENV
            
      - name: Install ARM64 target
        run: rustup target add aarch64-pc-windows-msvc
          
      - name: Build (MSVC ARM64)
        run: cargo build --release --target aarch64-pc-windows-msvc
        shell: bash

  build-windows-aarch64-gnu:
    name: Windows GNU (ARM64)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      # 1. 安装 MSYS2 ARM64 环境和依赖
      - name: Install MSYS2 & deps (MINGW64 ARM64)
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            mingw-w64-aarch64-gcc
            mingw-w64-aarch64-pkg-config
            mingw-w64-aarch64-openssl

      # 2. 设置 OpenSSL 环境变量，强制使用系统库
      - name: Set OpenSSL env
        shell: bash
        run: |
          echo "OPENSSL_NO_VENDOR=1" >> $GITHUB_ENV
          echo "OPENSSL_DIR=/clang64" >> $GITHUB_ENV
          echo "OPENSSL_LIB_DIR=/clang64/lib" >> $GITHUB_ENV
          echo "OPENSSL_INCLUDE_DIR=/clang64/include" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=/clang64/lib/pkgconfig" >> $GITHUB_ENV
          echo "PKG_CONFIG_ALLOW_CROSS=1" >> $GITHUB_ENV

      # 3. 安装 Rust ARM64 GNU target
      - name: Add aarch64-pc-windows-gnu target
        run: rustup target add aarch64-pc-windows-gnu

      # 4. 构建（在 MSYS2 shell 中使用 GNU 工具链）
      - name: Build (GNU ARM64)
        shell: msys2 {0}
        run: cargo build --release --target aarch64-pc-windows-gnu
