name: Build For Linux

on:
  push:
    tags:
      - 'v*'
      - 'v*-beta*'
      - 'v*-rc*'
      - 'nightly*'
  pull_request:
  workflow_dispatch:

jobs:
  build-linux-gnu-x86_64:
    name: Linux GNU (x86_64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Cache Rust toolchain & Cargo registry
        uses: actions/cache@v4
        with:
          path:
            - ~/.cargo/registry
            - ~/.cargo/git
            - ~/.rustup
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust (stable)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build (release)
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Rename artifact
        run: |
          mkdir -p dist
          cp target/x86_64-unknown-linux-gnu/release/msl-cli \
             dist/msl-cli-x86_64-unknown-linux-gnu

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: msl-cli-x86_64-unknown-linux-gnu
          path: dist/msl-cli-x86_64-unknown-linux-gnu

  build-linux-musl-x86_64:
    name: Linux MUSL (x86_64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Cache Rust toolchain & Cargo registry
        uses: actions/cache@v4
        with:
          path:
            - ~/.cargo/registry
            - ~/.cargo/git
            - ~/.rustup
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install musl toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools

      - name: Install Rust target
        run: rustup target add x86_64-unknown-linux-musl

      - name: Build (static musl)
        env:
          CC: x86_64-linux-musl-gcc
        run: cargo build --release --target x86_64-unknown-linux-musl

      - name: Rename artifact
        run: |
          mkdir -p dist
          cp target/x86_64-unknown-linux-musl/release/msl-cli \
             dist/msl-cli-x86_64-unknown-linux-musl

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: msl-cli-x86_64-unknown-linux-musl
          path: dist/msl-cli-x86_64-unknown-linux-musl
