name: Build For Windows

on:
  push:
    tags: 
      - 'v*'
      - 'v*-beta*'
      - 'v*-rc*'
      - 'nightly*'
  workflow_dispatch:
  pull_request:

jobs:
  build-windows-msvc-x86_64:
    name: Windows MSVC (x86_64)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install OpenSSL via vcpkg
        run: |
          vcpkg install openssl:x64-windows
          echo "OPENSSL_NO_VENDOR=1" >> $GITHUB_ENV

      - name: Build (MSVC x86_64)
        run: cargo build --release --target x86_64-pc-windows-msvc

  build-windows-gnu-x86_64:
    name: Windows GNU (x86_64)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install MSYS2 & OpenSSL (MINGW64)
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-openssl
            mingw-w64-x86_64-rust

      - name: Set OpenSSL env vars
        shell: bash
        run: |
          echo "OPENSSL_NO_VENDOR=1" >> $GITHUB_ENV
          echo "OPENSSL_DIR=/mingw64" >> $GITHUB_ENV
          echo "OPENSSL_LIB_DIR=/mingw64/lib" >> $GITHUB_ENV
          echo "OPENSSL_INCLUDE_DIR=/mingw64/include" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=/mingw64/lib/pkgconfig" >> $GITHUB_ENV
          echo "PKG_CONFIG_ALLOW_CROSS=1" >> $GITHUB_ENV

      - name: Build (GNU x86_64)
        shell: msys2 {0}
        run: cargo build --release --target x86_64-pc-windows-gnu
        
  build-windows-msvc-arm64: 
    name: Windows MSVC (ARM64)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        
      # 1. 安装 vcpkg
      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git C:\vcpkg
          C:\vcpkg\bootstrap-vcpkg.bat
          echo "VCPKG_ROOT=C:\vcpkg" >> $env:GITHUB_ENV

      # 2. 安装 ARM64 OpenSSL
      - name: Install OpenSSL (ARM64)
        run: |
          C:\vcpkg\vcpkg.exe install openssl:arm64-windows
          echo "OPENSSL_NO_VENDOR=1" >> $env:GITHUB_ENV
          echo "OPENSSL_DIR=C:\vcpkg\installed\arm64-windows" >> $env:GITHUB_ENV
          echo "OPENSSL_LIB_DIR=C:\vcpkg\installed\arm64-windows\lib" >> $env:GITHUB_ENV
          echo "OPENSSL_INCLUDE_DIR=C:\vcpkg\installed\arm64-windows\include" >> $env:GITHUB_ENV
            
      - name: Install ARM64 target
        run: rustup target add aarch64-pc-windows-msvc
          
      - name: Build (MSVC ARM64)
        run: cargo build --release --target aarch64-pc-windows-msvc
        shell: bash

  windows-i686-msvc:
    name: Windows MSVC (i686)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust (i686 MSVC)
        run: |
          rustup set profile minimal
          rustup install stable
          rustup target add i686-pc-windows-msvc

      - name: Build (i686 MSVC)
        run: cargo build --target i686-pc-windows-msvc --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mytool-windows-i686-msvc
          path: target/i686-pc-windows-msvc/release/mytool.exe

  windows-i686-gnu:
    name: Windows GNU (i686)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 安装 i686 GNU 构建所需的工具链和依赖
      - name: Install MSYS2 & deps (MINGW32)
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW32
          update: true
          install: >-
            mingw-w64-i686-gcc
            mingw-w64-i686-pkg-config
            mingw-w64-i686-openssl
            mingw-w64-i686-rust

      # 配置环境变量，强制使用系统 OpenSSL
      - name: Set OpenSSL env
        shell: bash
        run: |
          echo "OPENSSL_NO_VENDOR=1" >> $GITHUB_ENV
          echo "OPENSSL_DIR=/mingw32" >> $GITHUB_ENV
          echo "OPENSSL_LIB_DIR=/mingw32/lib" >> $GITHUB_ENV
          echo "OPENSSL_INCLUDE_DIR=/mingw32/include" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=/mingw32/lib/pkgconfig" >> $GITHUB_ENV
          echo "PKG_CONFIG_ALLOW_CROSS=1" >> $GITHUB_ENV

      # 安装 Rust i686 GNU target
      - name: Add i686 GNU target
        run: rustup target add i686-pc-windows-gnu

      # 构建（必须在 MSYS2 shell 中执行以调用 GNU 工具链）
      - name: Build (GNU i686)
        shell: msys2 {0}
        run: cargo build --release --target i686-pc-windows-gnu
