name: Build For Android

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - aarch64-linux-android
          - armv7-linux-androideabi

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Set up Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c
          add-to-path: true

      - name: Build OpenSSL for Android
        run: |
          curl -LO https://www.openssl.org/source/openssl-3.2.2.tar.gz
          tar xf openssl-3.2.2.tar.gz
          cd openssl-3.2.2

          if [ "${{ matrix.target }}" = "aarch64-linux-android" ]; then
            CONF="android-arm64"
            PREFIX="/opt/openssl-android-aarch64"
            CC_PATH="$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang"
          else
            CONF="android-arm"
            PREFIX="/opt/openssl-android-armv7"
            CC_PATH="$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang"
          fi

          ./Configure $CONF no-shared no-tests no-async no-afalgeng \
            --prefix=$PREFIX \
            CC=$CC_PATH

          make -j$(nproc) install_sw

      - name: Configure Cargo for Android
        run: |
          mkdir -p .cargo
          cat > .cargo/config.toml <<EOF
          [target.aarch64-linux-android]
          linker = "${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang"

          [target.armv7-linux-androideabi]
          linker = "${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang"
          EOF

      - name: Build Rust project
        env:
          OPENSSL_STATIC: "1"
          OPENSSL_DIR: ${{ matrix.target == 'aarch64-linux-android' && '/opt/openssl-android-aarch64' || '/opt/openssl-android-armv7' }}
          OPENSSL_LIB_DIR: ${{ matrix.target == 'aarch64-linux-android' && '/opt/openssl-android-aarch64/lib' || '/opt/openssl-android-armv7/lib' }}
          OPENSSL_INCLUDE_DIR: ${{ matrix.target == 'aarch64-linux-android' && '/opt/openssl-android-aarch64/include' || '/opt/openssl-android-armv7/include' }}
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: msl-cli-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/msl-cli
