name: Build For Linux

on:
  push:
    tags:
      - 'v*'
      - 'v*-beta*'
      - 'v*-rc*'
      - 'nightly*'
  pull_request:
  workflow_dispatch:

jobs:
  build-linux-gnu-x86_64:
    name: Linux GNU (x86_64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Cache Rust toolchain & Cargo registry
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          path: |
            $HOME/.cargo/registry
            $HOME/.cargo/git
            $HOME/.rustup

      - name: Install Rust (stable)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build (release)
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Rename artifact
        run: |
          mkdir -p dist
          cp target/x86_64-unknown-linux-gnu/release/msl-cli \
             dist/msl-cli-x86_64-unknown-linux-gnu

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: msl-cli-x86_64-unknown-linux-gnu
          path: dist/msl-cli-x86_64-unknown-linux-gnu

  build-linux-musl-x86_64:
    name: Linux MUSL (x86_64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Cache Rust toolchain & Cargo registry
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          path: |
            $HOME/.cargo/registry
            $HOME/.cargo/git
            $HOME/.rustup

      - name: Install musl toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools

      - name: Install Rust target
        run: rustup target add x86_64-unknown-linux-musl

      - name: Download and build OpenSSL for x86_64-musl
        shell: bash
        run: |
          set -euxo pipefail

          OPENSSL_VERSION=1.1.1w
          curl -sSL "https://www.openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz" \
            -o openssl.tar.gz
          tar -xzf openssl.tar.gz
          cd openssl-${OPENSSL_VERSION}

          export CC=musl-gcc
          export AR=ar
          export RANLIB=ranlib

          ./Configure linux-x86_64 no-shared no-tests \
            --prefix="$PWD/../openssl-install"
          make -j"$(nproc)" build_libs
          make install_sw

      - name: Build (static musl)
        env:
          CC: x86_64-linux-musl-gcc
          OPENSSL_DIR: ${{ github.workspace }}/openssl-install
          OPENSSL_LIB_DIR: ${{ github.workspace }}/openssl-install/lib
          OPENSSL_INCLUDE_DIR: ${{ github.workspace }}/openssl-install/include
        run: cargo build --release --target x86_64-unknown-linux-musl

      - name: Rename artifact
        run: |
          mkdir -p dist
          cp target/x86_64-unknown-linux-musl/release/msl-cli \
             dist/msl-cli-x86_64-unknown-linux-musl

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: msl-cli-x86_64-unknown-linux-musl
          path: dist/msl-cli-x86_64-unknown-linux-musl

  build-linux-gnu-aarch64:
    name: Linux GNU (aarch64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Cache Rust toolchain & Cargo registry
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          path: |
            $HOME/.cargo/registry
            $HOME/.cargo/git
            $HOME/.rustup

      - name: Install aarch64 glibc cross compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - name: Install Rust (stable)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Add aarch64-unknown-linux-gnu target
        run: rustup target add aarch64-unknown-linux-gnu

      - name: Build (release)
        env:
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
        run: cargo build --release --target aarch64-unknown-linux-gnu

      - name: Rename artifact
        run: |
          mkdir -p dist
          cp target/aarch64-unknown-linux-gnu/release/msl-cli \
             dist/msl-cli-aarch64-unknown-linux-gnu

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: msl-cli-aarch64-unknown-linux-gnu
          path: dist/msl-cli-aarch64-unknown-linux-gnu

  build-linux-musl-aarch64:
    name: Linux MUSL (aarch64)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 缓存 Zig 与 wrappers
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-zig-0.15.0-dev.1593+399bace2f
          path: |
            zig-dist
            zig-wrap

      - name: 安装 Zig 并生成智能 wrapper
        shell: bash
        run: |
          set -euxo pipefail
          curl -sSL "https://ziglang.org/builds/zig-x86_64-linux-0.15.0-dev.1593+399bace2f.tar.xz" -o zig.tar.xz
          mkdir zig-dist
          tar -xJf zig.tar.xz -C zig-dist --strip-components=1
          mkdir -p zig-wrap
          cat > zig-wrap/aarch64-linux-musl-cc << 'EOF'
          #!/usr/bin/env bash
          set -euxo pipefail
          args=()
          for a in "$@"; do case "$a" in --target=*|-target=*) ;; *) args+=("$a") ;; esac; done
          linking=true
          for a in "${args[@]}"; do case "$a" in -c|-S|-E) linking=false;; esac; done
          ZIG="$(dirname "$0")/../zig-dist/zig"
          LIBDIR="$(rustc --print sysroot)/lib/rustlib/aarch64-unknown-linux-musl/lib"
          if $linking; then
            exec "$ZIG" cc -target aarch64-linux-musl -nostartfiles -L"$LIBDIR" "${args[@]}"
          else
            exec "$ZIG" cc -target aarch64-linux-musl "${args[@]}"
          fi
          EOF
          cat > zig-wrap/zig-ar << 'EOF'
          #!/usr/bin/env bash
          set -euxo pipefail
          exec "$(dirname "$0")/../zig-dist/zig" ar "$@"
          EOF
          cat > zig-wrap/zig-ranlib << 'EOF'
          #!/usr/bin/env bash
          set -euxo pipefail
          exec "$(dirname "$0")/../zig-dist/zig" ranlib "$@"
          EOF
          chmod +x zig-wrap/*
          echo "$PWD/zig-dist" >> $GITHUB_PATH
          echo "$PWD/zig-wrap" >> $GITHUB_PATH
          
      - name: 构建 OpenSSL for aarch64-musl
        shell: bash
        run: |
          set -euxo pipefail

          OPENSSL_VERSION=1.1.1w
          curl -sSL "https://www.openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz" -o openssl.tar.gz
          tar -xzf openssl.tar.gz
          cd openssl-${OPENSSL_VERSION}

          # 显式指定交叉编译器，避免 cross-compile-prefix 拼接
          export CC="$PWD/../zig-wrap/aarch64-linux-musl-cc"
          export AR=zig-ar
          export RANLIB=zig-ranlib

          ./Configure linux-aarch64 no-shared no-tests \
            --prefix="$PWD/../openssl-install"
          make -j"$(nproc)" build_libs
          make install_sw   

      - name: 缓存 Rust & Cargo
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          path: |
            $HOME/.cargo/registry
            $HOME/.cargo/git
            $HOME/.rustup

      - name: 安装 Rust & 添加 MUSL target
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - run: rustup target add aarch64-unknown-linux-musl

      - name: 构建 (static musl via Zig)
        shell: bash
        env: 
          CC_aarch64_unknown_linux_musl: aarch64-linux-musl-cc
          AR_aarch64_unknown_linux_musl: zig-ar
          RANLIB_aarch64_unknown_linux_musl: zig-ranlib
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER: aarch64-linux-musl-cc
          OPENSSL_STATIC: "1"
          OPENSSL_DIR: ${{ github.workspace }}/openssl-install
        run: cargo build --release --target aarch64-unknown-linux-musl

      - name: 重命名 & 上传产物
        shell: bash
        run: |
          mkdir -p dist
          cp target/aarch64-unknown-linux-musl/release/msl-cli \
             dist/msl-cli-aarch64-unknown-linux-musl

      - uses: actions/upload-artifact@v4
        with:
          name: msl-cli-aarch64-unknown-linux-musl
          path: dist/msl-cli-aarch64-unknown-linux-musl
