name: Build For Windows

on:
  push:
    tags: 
      - 'v*'
      - 'v*-beta*'
      - 'v*-rc*'
      - 'nightly*'
  workflow_dispatch:
  pull_request:

jobs:
  build-windows-msvc:
    name: Windows MSVC
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install OpenSSL via vcpkg
        run: |
          vcpkg install openssl:x64-windows
          echo "OPENSSL_NO_VENDOR=1" >> $GITHUB_ENV

      - name: Build (MSVC)
        run: cargo build --release --target x86_64-pc-windows-msvc


  build-windows-gnu:
    name: Windows GNU
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install MSYS2 & OpenSSL (MINGW64)
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-openssl
            mingw-w64-x86_64-rust

      - name: Set OpenSSL env vars
        run: |
          echo "OPENSSL_NO_VENDOR=1" >> $GITHUB_ENV
          echo "OPENSSL_DIR=/mingw64" >> $GITHUB_ENV
          echo "OPENSSL_LIB_DIR=/mingw64/lib" >> $GITHUB_ENV
          echo "OPENSSL_INCLUDE_DIR=/mingw64/include" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=/mingw64/lib/pkgconfig" >> $GITHUB_ENV
          echo "PKG_CONFIG_ALLOW_CROSS=1" >> $GITHUB_ENV
        shell: bash

      - name: Build (GNU)
        shell: msys2 {0}
        run: cargo build --release --target x86_64-pc-windows-gnu
