name: Build For Windows

on:
  push:
    tags:
      - "v*"
      - "v*-beta*"
      - "v*-rc*"
      - "nightly*"
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Build Windows binary
        run: cargo build --release --target x86_64-pc-windows-msvc

      - name: Attach to Draft Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          draft: true
          prerelease: ${{ contains(github.ref, 'beta') || contains(github.ref, 'rc') || contains(github.ref, 'nightly') }}
          files: target/x86_64-pc-windows-msvc/release/msl-cli.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
