name: Build For Android

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - aarch64-linux-android
          - armv7-linux-androideabi

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Set up Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c
          add-to-path: true

      - name: Prepare OpenSSL source per-target
        run: |
          curl -LO https://www.openssl.org/source/openssl-3.2.2.tar.gz
          tar xf openssl-3.2.2.tar.gz
          mv openssl-3.2.2 "openssl-${{ matrix.target }}"

      - name: Build OpenSSL for Android
        shell: bash
        run: |
          set -eux
          export ANDROID_API=21
          export TOOLCHAIN_BIN="${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin"
          export PATH="${TOOLCHAIN_BIN}:${PATH}"
          export OPENSSL_CONFIG_OPTS="no-shared no-tests no-async no-afalgeng no-asm no-bf no-rc2 no-rc4 no-cast no-idea"
          if [ "${{ matrix.target }}" = "aarch64-linux-android" ]; then
            export CONF="android-arm64"
            export PREFIX="/opt/openssl-android-aarch64"
            export CC="${TOOLCHAIN_BIN}/aarch64-linux-android${ANDROID_API}-clang"
            export CROSS_COMPILE="aarch64-linux-android-"
          else
            export CONF="android-arm"
            export PREFIX="/opt/openssl-android-armv7"
            export CC="${TOOLCHAIN_BIN}/armv7a-linux-androideabi${ANDROID_API}-clang"
            export CROSS_COMPILE="arm-linux-androideabi-"
          fi
          export AR="${TOOLCHAIN_BIN}/llvm-ar"
          export RANLIB="${TOOLCHAIN_BIN}/llvm-ranlib"
          export NM="${TOOLCHAIN_BIN}/llvm-nm"
          cd "openssl-${{ matrix.target }}"
          perl ./Configure "${CONF}" ${OPENSSL_CONFIG_OPTS} --prefix="${PREFIX}" CC="${CC}"
          make clean
          make -j1 install_sw

      - name: Configure Cargo for Android
        run: |
          mkdir -p .cargo
          cat > .cargo/config.toml <<'EOF'
          [target.aarch64-linux-android]
          linker = "${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang"
          [target.armv7-linux-androideabi]
          linker = "${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang"
          EOF

      - name: Build Rust project
        env:
          OPENSSL_STATIC: "1"
          OPENSSL_DIR: ${{ matrix.target == 'aarch64-linux-android' && '/opt/openssl-android-aarch64' || '/opt/openssl-android-armv7' }}
          OPENSSL_LIB_DIR: ${{ matrix.target == 'aarch64-linux-android' && '/opt/openssl-android-aarch64/lib' || '/opt/openssl-android-armv7/lib' }}
          OPENSSL_INCLUDE_DIR: ${{ matrix.target == 'aarch64-linux-android' && '/opt/openssl-android-aarch64/include' || '/opt/openssl-android-armv7/include' }}
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: msl-cli-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/msl-cli
