name: Build & Release

on:
  push:
    tags:
      - "v*"
      - "v*-beta*"
      - "v*-rc*"
      - "nightly*"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build (${{ matrix.os }}-${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux GNU/x86_64/aarch64/armv7
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - os: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
          # Linux MUSL (static)
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
          - os: ubuntu-latest
            target: armv7-unknown-linux-musleabihf
          # Linux RISC-V
          - os: ubuntu-latest
            target: riscv64gc-unknown-linux-gnu
          # Windows MSVC/GNU/x86_64/aarch64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: windows-latest
            target: x86_64-pc-windows-gnu
          - os: windows-latest
            target: aarch64-pc-windows-msvc
          # macOS x86_64/aarch64
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
          # FreeBSD
          - os: ubuntu-latest
            target: x86_64-unknown-freebsd
          - os: ubuntu-latest
            target: aarch64-unknown-freebsd
          # OpenBSD
          - os: ubuntu-latest
            target: x86_64-unknown-openbsd
          # Android
          - os: ubuntu-latest
            target: aarch64-linux-android
          - os: ubuntu-latest
            target: armv7-linux-androideabi
          # iOS
          - os: macos-latest
            target: aarch64-apple-ios
          # WASM
          - os: ubuntu-latest
            target: wasm32-unknown-unknown
          - os: ubuntu-latest
            target: wasm32-wasi

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install cross
        run: cargo install cross

      - name: Get crate version
        shell: bash
        run: |
          VERSION=$(cargo metadata --format-version=1 --no-deps | jq -r '.packages[0].version')
          echo "VERSION=$VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build release binary
        run: cross build --release --target ${{ matrix.target }}

      - name: Prepare artifacts dir
        shell: bash
        run: |
          rm -rf artifacts
          mkdir -p artifacts

      - name: Package artifact
        shell: bash
        run: |
          set -euo pipefail

          VERSION="${{ env.VERSION }}"
          OS="${{ matrix.os }}"
          TARGET="${{ matrix.target }}"

          # 系统名
          if [[ "$OS" == "ubuntu-latest" ]]; then
            if [[ "$TARGET" == *"linux"* ]]; then
              SYS="linux"
            elif [[ "$TARGET" == *"freebsd"* ]]; then
              SYS="freebsd"
            elif [[ "$TARGET" == *"openbsd"* ]]; then
              SYS="openbsd"
            elif [[ "$TARGET" == *"android"* ]]; then
              SYS="android"
            elif [[ "$TARGET" == *"wasm"* ]]; then
              SYS="wasm"
            else
              SYS="ubuntu"
            fi
          elif [[ "$OS" == "macos-latest" ]]; then
            if [[ "$TARGET" == *"ios"* ]]; then
              SYS="ios"
            else
              SYS="macos"
            fi
          elif [[ "$OS" == "windows-latest" ]]; then
            SYS="windows"
          else
            SYS="$OS"
          fi

          # 架构名
          if [[ "$TARGET" == "x86_64"* ]]; then
            ARCH="x86_64"
          elif [[ "$TARGET" == "aarch64"* ]]; then
            ARCH="aarch64"
          elif [[ "$TARGET" == "armv7"* ]]; then
            ARCH="armv7"
          elif [[ "$TARGET" == "riscv64"* ]]; then
            ARCH="riscv64"
          elif [[ "$TARGET" == "wasm32"* ]]; then
            ARCH="wasm32"
          else
            ARCH="$TARGET"
          fi

          # 找到可执行文件
          if [[ "$SYS" == "windows" ]]; then
            BIN=$(find "target/${TARGET}/release" -type f -name "*.exe" -print -quit)
            OUT="msl-cli-${VERSION}-${SYS}-${ARCH}.exe"
          else
            BIN=$(find "target/${TARGET}/release" -type f -perm -u+x -print -quit)
            OUT="msl-cli-${VERSION}-${SYS}-${ARCH}"
          fi

          echo "BIN=$BIN"
          echo "OUT=$OUT"

          if [[ -z "$BIN" ]]; then
            echo "Error: No binary found for $TARGET" >&2
            ls "target/${TARGET}/release"
            exit 1
          fi

          cp "$BIN" "artifacts/$OUT"

          # SHA256 校验
          if [[ "$SYS" == "windows" ]]; then
            powershell -Command "Get-FileHash -Algorithm SHA256 '$BIN' | Select-Object -ExpandProperty Hash | Out-File -Encoding ascii 'artifacts/${OUT}.sha256'"
          else
            shasum -a 256 "$BIN" > "artifacts/${OUT}.sha256"
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: msl-cli-${{ env.VERSION }}-${{ matrix.target }}
          path: artifacts/*

  release:
    name: Publish Release
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**
          prerelease: ${{ contains(github.ref, 'beta') || contains(github.ref, 'rc') || contains(github.ref, 'nightly') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
