name: Rust Release

on:
  push:
    tags:
      - "v*"
      - "v*-beta*"
      - "v*-rc*"
      - "nightly*"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build (${{ matrix.os }}-${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install cross
        run: cargo install cross

      - name: Get crate version
        id: get_version
        shell: bash
        run: |
          VERSION=$(cargo metadata --format-version=1 --no-deps | jq -r '.packages[0].version')
          echo "VERSION=$VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build release binary
        run: cross build --release --target ${{ matrix.target }}

      - name: Prepare artifacts dir
        shell: bash
        run: |
          rm -rf artifacts
          mkdir -p artifacts

      - name: Package artifact
        shell: bash
        run: |
          set -euo pipefail

          VERSION="${{ env.VERSION }}"
          OS="${{ matrix.os }}"
          TARGET="${{ matrix.target }}"

          # 解析系统和架构
          if [[ "$OS" == "ubuntu-latest" ]]; then
            SYS="linux"
          elif [[ "$OS" == "macos-latest" ]]; then
            SYS="macos"
          elif [[ "$OS" == "windows-latest" ]]; then
            SYS="windows"
          else
            SYS="$OS"
          fi

          # 解析架构
          if [[ "$TARGET" == "x86_64-"* ]]; then
            ARCH="x86_64"
          elif [[ "$TARGET" == "aarch64-"* ]]; then
            ARCH="aarch64"
          else
            ARCH="$TARGET"
          fi

          # 查找可执行文件
          if [[ "$SYS" == "windows" ]]; then
            BIN=$(find "target/${TARGET}/release" -type f -name "*.exe" -print -quit)
            OUT="msl-cli-${VERSION}-${SYS}-${ARCH}.exe"
          else
            BIN=$(find "target/${TARGET}/release" -type f -perm -u+x -print -quit)
            OUT="msl-cli-${VERSION}-${SYS}-${ARCH}"
          fi

          echo "BIN=$BIN"
          echo "OUT=$OUT"

          if [[ -z "$BIN" ]]; then
            echo "Error: No binary found for $TARGET" >&2
            ls "target/${TARGET}/release"
            exit 1
          fi

          cp "$BIN" "artifacts/$OUT"

          # SHA256 校验
          if [[ "$SYS" == "windows" ]]; then
            powershell -Command "Get-FileHash -Algorithm SHA256 '$BIN' | Select-Object -ExpandProperty Hash | Out-File -Encoding ascii 'artifacts/${OUT}.sha256'"
          else
            shasum -a 256 "$BIN" > "artifacts/${OUT}.sha256"
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: msl-cli-${{ env.VERSION }}-${{ matrix.target }}
          path: artifacts/*

  tag-and-release:
    name: Auto Tag & Publish Release
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    permissions:
      contents: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Setup Git user
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      # 读取 Cargo.toml 的版本号
      - name: Get crate version
        id: get_version
        shell: bash
        run: |
          VERSION=$(cargo metadata --format-version=1 --no-deps | jq -r '.packages[0].version')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      # 自动创建 tag，并保证和 Cargo.toml 版本一致
      - name: Create tag if not exists
        run: |
          TAG="v${{ steps.get_version.outputs.version }}"
          git fetch --tags
          if ! git rev-parse "$TAG" >/dev/null 2>&1; then
            git tag "$TAG"
            git push origin "$TAG"
          else
            echo "Tag $TAG already exists"
          fi

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: v${{ env.VERSION }}
          files: artifacts/**
          prerelease: ${{ contains(github.ref, 'beta') || contains(github.ref, 'rc') || contains(github.ref, 'nightly') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
