name: Rust Release

on:
  push:
    tags:
      - "v*"        
      - "v0-beta3.7"  
      - "v*-rc*"   
      - "nightly*"  
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build (${{ matrix.os }}-${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      # ✅ 安装构建依赖
      - name: Install build deps (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y musl-tools pkg-config libssl-dev jq

      - name: Install jq on Windows
        if: runner.os == 'Windows'
        run: choco install jq

      - name: Get crate version
        shell: bash
        run: |
          VERSION=$(cargo metadata --format-version=1 --no-deps | jq -r '.packages[0].version')
          echo "VERSION=$VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # 安装交叉编译工具链（Linux aarch64）
      - name: Install cross compiler
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu

      # 构建 aarch64 OpenSSL 并设置环境变量
      - name: Build OpenSSL for aarch64
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          OPENSSL_VERSION=1.1.1w
          wget https://www.openssl.org/source/openssl-$OPENSSL_VERSION.tar.gz
          tar xf openssl-$OPENSSL_VERSION.tar.gz
          cd openssl-$OPENSSL_VERSION
          CC=aarch64-linux-gnu-gcc ./Configure linux-aarch64 no-shared no-tests --prefix=$PWD/../openssl-aarch64
          make -j$(nproc)
          make install_sw
          cd ..
          echo "OPENSSL_DIR=$PWD/openssl-aarch64" >> $GITHUB_ENV
          echo "OPENSSL_LIB_DIR=$PWD/openssl-aarch64/lib" >> $GITHUB_ENV
          echo "OPENSSL_INCLUDE_DIR=$PWD/openssl-aarch64/include" >> $GITHUB_ENV
          echo "PKG_CONFIG_ALLOW_CROSS=1" >> $GITHUB_ENV

      - name: Build release binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Prepare artifacts dir
        shell: bash
        run: |
          rm -rf artifacts
          mkdir -p artifacts

      - name: Package artifact
        shell: bash
        run: |
          set -euo pipefail

          echo "Checking for built binaries in target/${{ matrix.target }}/release"
          if [[ "$RUNNER_OS" == "Windows" ]]; then
              BIN=$(find "target/${{ matrix.target }}/release" -type f -name "*.exe" -print -quit)
          else
              BIN=$(find "target/${{ matrix.target }}/release" -type f -perm -u+x -print -quit)
          fi

          echo "BIN=$BIN"

          if [[ -z "$BIN" ]]; then
              echo "Error: No binary found for ${{ matrix.target }}" >&2
              ls "target/${{ matrix.target }}/release"
              exit 1
          fi

          cp "$BIN" artifacts/

          # SHA256 校验
          if [[ "$RUNNER_OS" == "Windows" ]]; then
              powershell -Command "Get-FileHash -Algorithm SHA256 '$BIN' | Select-Object -ExpandProperty Hash | Out-File -Encoding ascii 'artifacts/${{ env.VERSION }}-${{ matrix.target }}.sha256'"
          else
              shasum -a 256 "$BIN" > "artifacts/${{ env.VERSION }}-${{ matrix.target }}.sha256"
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: msl-cli-${{ env.VERSION }}-${{ matrix.target }}
          path: artifacts/*

  release:
    name: Publish Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**
          prerelease: ${{ contains(github.ref, 'beta') || contains(github.ref, 'rc') || contains(github.ref, 'nightly') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
