name: Rust Release

on:
  push:
    tags:
      - "v*"
      - "v*-beta*"
      - "v*-rc*"
      - "nightly*"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build (${{ matrix.os }}-${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install cross
        run: cargo install cross

      - name: Get crate version
        id: get_version
        shell: bash
        run: |
          VERSION=$(cargo metadata --format-version=1 --no-deps | jq -r '.packages[0].version')
          echo "VERSION=$VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build release binary
        run: cross build --release --target ${{ matrix.target }}

      - name: Prepare artifacts dir
        shell: bash
        run: |
          rm -rf artifacts
          mkdir -p artifacts

      - name: Package artifact
        shell: bash
        run: |
          set -euo pipefail

          echo "Checking for built binaries in target/${{ matrix.target }}/release"
          if [[ "$RUNNER_OS" == "Windows" ]]; then
              BIN=$(find "target/${{ matrix.target }}/release" -type f -name "*.exe" -print -quit)
          else
              BIN=$(find "target/${{ matrix.target }}/release" -type f -perm -u+x -print -quit)
          fi

          echo "BIN=$BIN"

          if [[ -z "$BIN" ]]; then
              echo "Error: No binary found for ${{ matrix.target }}" >&2
              ls "target/${{ matrix.target }}/release"
              exit 1
          fi

          cp "$BIN" artifacts/

          # SHA256 校验
          if [[ "$RUNNER_OS" == "Windows" ]]; then
              powershell -Command "Get-FileHash -Algorithm SHA256 '$BIN' | Select-Object -ExpandProperty Hash | Out-File -Encoding ascii 'artifacts/${{ env.VERSION }}-${{ matrix.target }}.sha256'"
          else
              shasum -a 256 "$BIN" > "artifacts/${{ env.VERSION }}-${{ matrix.target }}.sha256"
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: msl-cli-${{ env.VERSION }}-${{ matrix.target }}
          path: artifacts/*

  tag-and-release:
    name: Auto Tag & Publish Release
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    permissions:
      contents: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Setup Git user
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Get version from build job
        run: echo "VERSION=$(cat artifacts/${{ needs.build.outputs.version }})" >> $GITHUB_ENV

      - name: Create tag
        run: |
          TAG="v${{ env.VERSION }}"
          echo "TAG=$TAG"
          git tag $TAG
          git push origin $TAG

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: v${{ env.VERSION }}
          files: artifacts/**
          prerelease: ${{ contains(github.ref, 'beta') || contains(github.ref, 'rc') || contains(github.ref, 'nightly') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
